#main thread
main:
  #Service unique identifier
  type: 3
  id: 1
  #Specify timezone(default CST)
  timezone: "/usr/share/zoneinfo/UTC"
  #Specify the log directory.
  logdir: "./mylog/"
  #Specify the server verbosity level(DEBUG INFO TRACE WARN ERROR)
  loglevel: "DEBUG"
  #Print log to teminal
  verbose: true
  #Split log file when file is larger than 64MB
  isolate: true
  #Specify the web root directory.
  webroot: "."
  #Redirect to url specified.
  redirecturl: "https://dev.wgnice.com/%s"
  redirectstatus: 301
  #Specify the public key private key.
  certificatefile: "../config/server.crt"
  privatekeyfile: "../config/server.key"
  #Setup allow origin
  alloworigin: true
  #Log module name
  modulename: "pico"
  #maxframe size(bytes)
  maxframesize: 65536
  mongourl: "mongodb://GAME:game12345@poker.demo.mongodb:5100,poker.demo.mongodb:5101,poker.demo.mongodb:5102/?authSource=admin&replicaSet=poker_demo"
  #Redis connect url
  redisurl: ["tcp://Ch1904@poker.demo.mongodb:5002/4"]

#worker thread
workers: [{ hosts: ["http://*:8080", "https://*:8443"] }]
